export const data = [
    {
        id: 1,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/966/big/2c160266117138966_ci.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        recommended: true,
        constructionType: "panel",
        furnished: true,
        floor: 2,
        size: 75,
        parking: 'Designated spot',

    },
    {
        id: 2,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/813/big/2c160035268340813_bF.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        recommended: true,
        constructionType: "panel",
        furnished: true,
        floor: 2,
        size: 75,
        parking: 'Designated spot',
    },
    {
        id: 3,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/774/big/2c160155846911774_zx.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        recommended: true,
        constructionType: "EPK",
        furnished: true,
        floor: 2,
        size: 62,
        parking: 'Designated spot',
    },
    {
        id: 4,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/795/big/2c160275339054795_Zq.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        recommended: true,
        constructionType: "EPK",
        furnished: true,
        floor: 1,
        size: 50,
        parking: 'Garage',
    },
    {
        id: 5,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/966/big/2c160266117138966_ci.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 1,
        size: 50,
        parking: 'Garage',
    },
    {
        id: 6,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/813/big/2c160035268340813_bF.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 1,
        size: 50,
        parking: 'Garage',
    },
    {
        id: 7,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/774/big/2c160155846911774_zx.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: false,
        floor: 4,
        size: 100,
        parking: 'Garage',
    },
    {
        id: 8,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/795/big/2c160275339054795_Zq.jpg',
        area: 'Levski',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: false,
        floor: 12,
        size: 100,
        parking: 'Designated spot',
    },
    {
        id: 9,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/966/big/2c160266117138966_ci.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: false,
        floor: 12,
        size: 98,
        parking: 'Designated spot',
    },
    {
        id: 10,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/813/big/2c160035268340813_bF.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: false,
        floor: 8,
        size: 101,
        parking: 'Garage',
    },
    {
        id: 11,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/774/big/2c160155846911774_zx.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 8,
        size: 101,
        parking: 'Garage',
    },
    {
        id: 12,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/795/big/2c160275339054795_Zq.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 4,
        size: 45,
        parking: 'Designated spot',
    },
    {
        id: 13,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/966/big/2c160266117138966_ci.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 3,
        size: 51,
        parking: 'Garage',
    },
    {
        id: 14,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/813/big/2c160035268340813_bF.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 3,
        size: 51,
        parking: 'Garage',
    },
    {
        id: 5,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/774/big/2c160155846911774_zx.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 3,
        size: 51,
        parking: 'Garage',
    },
    {
        id: 16,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/795/big/2c160275339054795_Zq.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: false,
        floor: 7,
        size: 69,
        parking: 'Designated spot',
    },
    {
        id: 17,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/966/big/2c160266117138966_ci.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: false,
        floor: 7,
        size: 69,
        parking: 'Designated spot',
    },
    {
        id: 18,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/813/big/2c160035268340813_bF.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: false,
        floor: 7,
        size: 69,
        parking: 'Designated spot',
    },
    {
        id: 19,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/774/big/2c160155846911774_zx.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 6,
        size: 82,
        parking: 'Garage',
    },
    {
        id: 20,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/795/big/2c160275339054795_Zq.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 2,
        size: 86,
        parking: 'Garage',
    },
    {
        id: 21,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/966/big/2c160266117138966_ci.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 6,
        size: 82,
        parking: 'Garage',
    },
    {
        id: 22,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/813/big/2c160035268340813_bF.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 10,
        size: 120,
        parking: 'Designated spot',
    },
    {
        id: 23,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/774/big/2c160155846911774_zx.jpg',
        area: 'Mladost 1',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 10,
        size: 120,
        parking: 'Garage',
    },
    {
        id: 24,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/795/big/2c160275339054795_Zq.jpg',
        area: 'Mladost 1',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 10,
        size: 120,
        parking: 'Garage',
    },
] 