export const profile = {
    username: 'Slavi',
    password: 'root1',
    favoriteApartments: [{
        id: 21,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/966/big/2c160266117138966_ci.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "EPK",
        furnished: true,
        floor: 6,
        size: 82,
        parking: 'Garage',
    },
    {
        id: 22,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/813/big/2c160035268340813_bF.jpg',
        area: 'Briz',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 10,
        size: 120,
        parking: 'Designated spot',
    },
    {
        id: 23,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/774/big/2c160155846911774_zx.jpg',
        area: 'Mladost 1',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 10,
        size: 120,
        parking: 'Garage',
    },
    {
        id: 24,
        title: '2-bedroom apartment, Levski, Zora St, 85 sq.m,',
        headImg: 'https://imot.focus.bg/photosimotbg/2/795/big/2c160275339054795_Zq.jpg',
        area: 'Mladost 1',
        price: 220,
        rooms: 2,
        constructionType: "panel",
        furnished: true,
        floor: 10,
        size: 120,
        parking: 'Garage',
    },
    ],
}